### ISSUE TITLE
Fact checking workflow doesn't work with PRs from forks

### ISSUE THREAD

**Issue by danisztls** [1712n/dni-website#33]
Follow up #24 

[Pull request](https://github.com/1712n/dni-website/pull/28)
[Job console](https://github.com/1712n/dni-website/actions/runs/5072609947/jobs/9110531011?pr=28)

In a PR, the runtime context is the branch origin repository. This is a GH security policy and otherwise anyone could submit a malicious PR to leak secrets. So the workflow fails with PRs from forked repos because it will run in the wrong context without the GH read/write and the OpenAI key.

I have to study an alternative besides denying PRs from forked repos or adopting a self-hosted runner.

**Comment by danisztls** [comment]
@marina-chibizova

**Comment by marina-chibizova** [comment]
@danisztls is it possible to trigger the action manually? would be a nice hot fix option for people checking the existing PRs

**Comment by marina-chibizova** [comment]
got it, let's not get into secret injections.

> You can have a preprod branch for people to submit their PRs and have an action that creates another PR to main on merge.

Proceeding with this option then?

**Comment by danisztls** [comment]
> Proceeding with this option then?

**Comment by danisztls** [comment]
> Proceeding with this option then?

Probably.

Alternatively we can also use the fact checking script as a step of deployment so it will trigger on a push event to main and fail to deploy if an incorrect statement is found. The script can be modified to create an issue in the repo. Would this be preferrable over the prepod & PR flow?
